(function () {
const RAW_QUESTION_BANK = [
  {
    id: "clarify_pain_location",
    text: "你說的疼痛或不舒服，位置比較接近哪裡？",
    asksFor: ["painLocationClarification"],
    symptoms: ["pain", "ambiguous_location"],
    ambiguityType: "pain_location",
    keywords: ["下面痛", "下面不舒服", "那邊痛", "私密處", "尿道痛", "生殖器痛", "會陰", "下腹痛", "pain down there", "private area pain", "hurts down there"],
    value: "病人常無法精準區分尿道、下腹、生殖器或會陰疼痛；先定位可降低誤導後續題目的風險。",
    explanation: "這是 clarification question，不是診斷題。目的是把模糊位置轉成可用資訊。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.92,
    clinicalWorkflowValue: 0.92,
    safetyPriority: 0.62,
    nextUsefulWhen: ["使用者說下面痛、那邊痛、私密處不舒服、或痛的位置不清楚"],
    skipWhen: ["已經回答 painLocationClarification", "使用者已明確說尿尿時尿道刺痛、下腹痛、生殖器痛或會陰痛"],
    options: ["尿尿時尿道刺痛", "下腹悶痛", "生殖器或陰囊疼痛", "會陰或肛門前方疼痛", "不確定"]
  },
  {
    id: "clarify_urinary_symptom_type",
    text: "你說的「尿尿怪怪的」比較接近哪一種？",
    asksFor: ["urinarySymptomClarification"],
    symptoms: ["ambiguous_urinary"],
    ambiguityType: "urinary_symptom_type",
    keywords: ["尿尿怪怪", "怪怪的", "不舒服", "怪", "說不出來", "不順", "weird", "not sure", "i don't know"],
    value: "病人只說怪怪的時，先區分頻率、疼痛、排尿困難、血尿或漏尿，避免 similarity 直接誤判方向。",
    explanation: "這題先把模糊主訴拆成可追問的症狀類型。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.94,
    clinicalWorkflowValue: 0.94,
    safetyPriority: 0.58,
    nextUsefulWhen: ["使用者只說尿尿怪怪的、下面不舒服、或無法說清楚是哪一類泌尿問題"],
    skipWhen: ["已經回答 urinarySymptomClarification", "使用者已明確指出夜尿、急尿、尿痛、血尿、漏尿或尿不出來"],
    options: ["次數變多或晚上起來尿", "尿尿會痛或灼熱", "尿不太出來或尿流變弱", "看到紅色或茶色尿", "漏尿", "不確定"]
  },
  {
    id: "duration",
    text: "這個問題大約多久了？",
    asksFor: ["duration"],
    symptoms: ["general"],
    keywords: ["多久", "開始", "最近", "today", "week", "month", "duration"],
    value: "建立病程，讓後續摘要能區分急性與慢性問題。",
    explanation: "先建立病程，避免只有症狀方向但缺少時間脈絡。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.82,
    clinicalWorkflowValue: 0.82,
    safetyPriority: 0.25,
    nextUsefulWhen: ["任何主訴已出現但尚未建立病程"],
    skipWhen: ["已經回答 duration"],
    options: ["今天", "1 到 7 天", "1 到 4 週", "超過 1 個月", "不確定"]
  },
  {
    id: "bother_score",
    text: "如果 0 分是不困擾、10 分是非常困擾，現在大約幾分？",
    asksFor: ["botherScore"],
    symptoms: ["general"],
    keywords: ["困擾", "嚴重", "受不了", "bother", "severity"],
    value: "量化病人主觀困擾，協助醫師快速抓到優先關切。",
    explanation: "補足病人主觀負擔，而不是推論診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.76,
    clinicalWorkflowValue: 0.76,
    safetyPriority: 0.2,
    nextUsefulWhen: ["已有主訴但缺少困擾程度"],
    skipWhen: ["已經回答 botherScore"],
    options: ["0-2", "3-5", "6-8", "9-10", "不確定"]
  },
  {
    id: "nocturia_count",
    text: "晚上睡著後通常會起來尿尿幾次？",
    asksFor: ["nocturiaCount"],
    symptoms: ["frequency", "nocturia", "urgency"],
    keywords: ["晚上", "夜尿", "睡覺", "起來尿", "nocturia", "night"],
    value: "使用者提到夜尿時，這題最能補足頻率與負擔。",
    explanation: "夜尿被提到時，次數是最直接的下一個缺口。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.28,
    nextUsefulWhen: ["使用者提到晚上起來尿、夜尿或睡眠被尿意打斷"],
    skipWhen: ["已經回答 nocturiaCount"],
    options: ["0 次", "1 次", "2 次", "3 次以上", "不確定"]
  },
  {
    id: "urgency",
    text: "會突然很想尿，而且很難忍住嗎？",
    asksFor: ["urgency"],
    symptoms: ["frequency", "urgency", "leakage"],
    keywords: ["急", "忍不住", "來不及", "urgency", "rush"],
    value: "釐清是否有急尿，決定是否需要追問漏尿或頻率。",
    explanation: "急尿會影響後續是否追問漏尿與情境。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.86,
    clinicalWorkflowValue: 0.86,
    safetyPriority: 0.24,
    nextUsefulWhen: ["使用者提到急、忍不住或來不及"],
    skipWhen: ["已經回答 urgency"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "daytime_frequency",
    text: "白天大約尿尿幾次？",
    asksFor: ["daytimeFrequencyCount"],
    symptoms: ["frequency", "nocturia", "urgency"],
    keywords: ["頻尿", "一直跑廁所", "白天", "次數", "frequent"],
    value: "使用者描述頻尿時，用區間補足白天頻率。",
    explanation: "白天次數讓頻尿描述從模糊感受變成可摘要資訊。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.84,
    clinicalWorkflowValue: 0.84,
    safetyPriority: 0.22,
    nextUsefulWhen: ["使用者提到頻尿、一直跑廁所或白天次數增加"],
    skipWhen: ["已經回答 daytimeFrequencyCount"],
    options: ["1 到 4 次", "5 到 8 次", "9 到 12 次", "超過 12 次", "不確定"]
  },
  {
    id: "leakage",
    text: "最近 4 週有尿不小心漏出來嗎？",
    asksFor: ["leakage"],
    symptoms: ["leakage", "urgency"],
    keywords: ["漏尿", "滲出", "褲子", "護墊", "leak", "incontinence"],
    value: "當使用者提到忍不住或漏尿，先建立是否發生漏尿。",
    explanation: "先確認是否真的有漏尿，再決定是否追問量與情境。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.82,
    clinicalWorkflowValue: 0.82,
    safetyPriority: 0.22,
    nextUsefulWhen: ["使用者提到漏尿、忍不住、護墊或尿會滲出"],
    skipWhen: ["已經回答 leakage"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "leakage_trigger",
    text: "漏尿最常在什麼情況發生？",
    asksFor: ["leakageTriggers"],
    symptoms: ["leakage", "urgency"],
    keywords: ["咳嗽", "笑", "運動", "睡覺", "來不及", "trigger"],
    value: "漏尿已成立時，這題補足情境，讓護理端與醫師摘要更可用。",
    explanation: "漏尿情境是護理端補問與醫師摘要的重要背景。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.18,
    nextUsefulWhen: ["已知道有漏尿或使用者描述來不及、咳嗽笑運動時漏"],
    skipWhen: ["尚未知道是否漏尿", "已經回答 leakageTriggers"],
    options: ["來不及到廁所", "咳嗽、笑或運動", "睡覺時", "沒有明顯原因", "不確定"]
  },
  {
    id: "unable_to_urinate",
    text: "有很想尿卻尿不太出來，或完全尿不出來嗎？",
    asksFor: ["unableToUrinate"],
    symptoms: ["voiding", "retention"],
    keywords: ["尿不出來", "尿流弱", "排尿困難", "卡住", "retention", "weak stream"],
    value: "排尿困難方向的核心問題，也能觸發現場優先告知提醒。",
    explanation: "排尿困難需要先確認是否存在，尤其避免漏掉仍尿不出來的情況。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.88,
    clinicalWorkflowValue: 0.88,
    safetyPriority: 0.55,
    nextUsefulWhen: ["使用者提到尿不出來、尿流弱、卡住或排尿困難"],
    skipWhen: ["已經回答 unableToUrinate"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "current_retention",
    text: "現在是否還尿不出來？",
    asksFor: ["currentlyUnableToUrinate"],
    symptoms: ["voiding", "retention"],
    keywords: ["現在", "還是", "尿不出來", "retention", "urgent"],
    value: "若現在仍尿不出來，這是現場優先告知資訊。",
    explanation: "這題只確認目前狀態，避免把急需現場告知的資訊埋在摘要後面。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.8,
    clinicalWorkflowValue: 0.8,
    safetyPriority: 0.85,
    nextUsefulWhen: ["已知道有尿不出來，需確認現在是否仍發生"],
    skipWhen: ["尚未知道是否尿不出來", "已經回答 currentlyUnableToUrinate"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "pain_burning",
    text: "尿尿時會痛、刺痛或灼熱嗎？",
    asksFor: ["painBurning"],
    symptoms: ["pain", "infection"],
    keywords: ["痛", "刺痛", "灼熱", "感染", "burning", "burns", "pain", "pee"],
    value: "使用者提到疼痛或感染疑慮時，先補足排尿疼痛。",
    explanation: "若疼痛位置已清楚指向尿尿時刺痛，這題補足尿痛/灼熱。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.84,
    clinicalWorkflowValue: 0.84,
    safetyPriority: 0.45,
    nextUsefulWhen: ["使用者提到尿尿會痛、刺痛、灼熱或感染疑慮"],
    skipWhen: ["疼痛位置仍模糊時應先問位置釐清", "已經回答 painBurning"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "systemic_symptoms",
    text: "最近有發燒、發冷或腰部兩側痛嗎？",
    asksFor: ["systemicSymptoms"],
    symptoms: ["pain", "infection", "red_flag"],
    keywords: ["發燒", "發冷", "腰痛", "腰側", "fever", "chills", "flank"],
    value: "感染疑慮下，這題補足需要現場優先確認的症狀。",
    explanation: "在感染/疼痛方向中，發燒、發冷、腰側痛需要優先標出。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.88,
    clinicalWorkflowValue: 0.88,
    safetyPriority: 0.78,
    nextUsefulWhen: ["使用者提到尿痛、感染疑慮、發燒、發冷或腰側痛"],
    skipWhen: ["已經回答 systemicSymptoms"],
    answerType: "multi_choice",
    options: ["發燒", "發冷", "腰部兩側痛", "以上都沒有", "不確定"]
  },
  {
    id: "visible_blood",
    text: "有看過尿液變紅、茶色，或看到血塊嗎？",
    asksFor: ["visibleBlood"],
    symptoms: ["hematuria", "red_flag"],
    keywords: ["血尿", "紅色", "茶色", "血塊", "blood", "clot"],
    value: "血尿是看診前摘要必須標出的病人回報。",
    explanation: "先確認是否看見紅色/茶色尿或血塊，不做診斷。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.82,
    nextUsefulWhen: ["使用者提到血尿、紅色尿、茶色尿或血塊"],
    skipWhen: ["已經回答 visibleBlood"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "hematuria_pattern",
    text: "如果有看到血尿，是一次、反覆，還是最近幾乎每次都有？",
    asksFor: ["hematuriaPattern"],
    symptoms: ["hematuria", "red_flag"],
    keywords: ["一次", "反覆", "每次", "血尿", "blood"],
    value: "血尿已成立時，這題補足發生型態。",
    explanation: "血尿已被標出後，再補足一次/反覆/每次的型態。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.66,
    nextUsefulWhen: ["已知道看見血尿或血塊，需補足發生型態"],
    skipWhen: ["尚未知道是否血尿", "已經回答 hematuriaPattern"],
    options: ["一次", "不只一次", "最近幾乎每次都有", "不確定"]
  },
  {
    id: "chief_complaint_open",
    text: "今天最主要想讓醫師知道的泌尿問題是什麼？",
    asksFor: ["chiefComplaint"],
    symptoms: ["general"],
    keywords: ["主要", "最困擾", "what brings", "main concern", "chief complaint"],
    value: "建立病人的主訴入口，讓後續 adaptive ranking 有基準。",
    explanation: "這是門診前病史蒐集入口，不做診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.86,
    clinicalWorkflowValue: 0.86,
    safetyPriority: 0.18,
    nextUsefulWhen: ["尚未有主訴或需要重新整理病人最在意的問題"],
    skipWhen: ["已經回答 chiefComplaint"],
    answerType: "open_text",
    options: ["自由輸入"]
  },
  {
    id: "most_bothersome_symptom",
    text: "這些症狀裡，哪一個目前最困擾你？",
    asksFor: ["mostBothersomeSymptom"],
    symptoms: ["general"],
    keywords: ["最困擾", "bothers most", "main symptom"],
    value: "多症狀時先抓出病人最想解決的主軸。",
    explanation: "排序病人的主觀優先順序，幫助醫師快速閱讀。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.16,
    nextUsefulWhen: ["病人同時提到多個症狀，需知道最困擾的一項"],
    skipWhen: ["已經回答 mostBothersomeSymptom"],
    options: ["夜尿或頻尿", "尿急或忍不住", "尿痛或灼熱", "血尿", "排尿困難", "其他"]
  },
  {
    id: "symptom_start_pattern",
    text: "症狀是突然開始，還是慢慢變明顯？",
    asksFor: ["symptomStartPattern"],
    symptoms: ["general"],
    keywords: ["突然", "慢慢", "開始", "sudden", "gradual"],
    value: "補足症狀起始方式，讓病程比單純日期更可讀。",
    explanation: "這題補足起始方式，不推論疾病。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.72,
    clinicalWorkflowValue: 0.72,
    safetyPriority: 0.18,
    nextUsefulWhen: ["已知道症狀但缺少起始方式"],
    skipWhen: ["已經回答 symptomStartPattern"],
    options: ["突然開始", "慢慢變明顯", "反覆出現", "不確定"]
  },
  {
    id: "nocturia_sleep_impact",
    text: "晚上起來尿尿會不會明顯影響睡眠？",
    asksFor: ["nocturiaSleepImpact"],
    symptoms: ["nocturia", "frequency"],
    keywords: ["睡眠", "睡不好", "醒來", "sleep", "wake"],
    value: "夜尿已出現時，睡眠影響是病人端有感的負擔資訊。",
    explanation: "補足夜尿對睡眠的影響，讓摘要更貼近病人負擔。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.16,
    nextUsefulWhen: ["使用者提到晚上起來尿或睡眠被打斷"],
    skipWhen: ["已經回答 nocturiaSleepImpact"],
    options: ["不太影響", "有一點影響", "明顯影響", "不確定"]
  },
  {
    id: "fluid_context_evening",
    text: "晚上睡前是否常喝很多水、茶、咖啡或酒？",
    asksFor: ["fluidContext"],
    symptoms: ["nocturia", "frequency", "context"],
    keywords: ["喝水", "茶", "咖啡", "酒", "fluid", "coffee", "tea"],
    value: "夜尿/頻尿方向中，補足可能影響症狀的生活背景。",
    explanation: "這題只收集背景，不建議限制飲食或治療。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.64,
    clinicalWorkflowValue: 0.64,
    safetyPriority: 0.12,
    nextUsefulWhen: ["夜尿或頻尿已出現，且核心症狀欄位已有部分答案"],
    skipWhen: ["已經回答 fluidContext"],
    options: ["很少", "有時候", "經常", "不確定"]
  },
  {
    id: "urgency_hold_time",
    text: "一有尿意後，通常能忍多久？",
    asksFor: ["urgencyHoldTime"],
    symptoms: ["urgency", "leakage"],
    keywords: ["忍多久", "忍住", "hold", "urge"],
    value: "急尿已出現時，補足對日常活動的影響程度。",
    explanation: "量化急尿的可忍受時間，避免只留下模糊描述。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.75,
    clinicalWorkflowValue: 0.75,
    safetyPriority: 0.16,
    nextUsefulWhen: ["已知道有急尿或忍不住"],
    skipWhen: ["已經回答 urgencyHoldTime"],
    options: ["可以忍 10 分鐘以上", "大約 5 到 10 分鐘", "不到 5 分鐘", "幾乎來不及", "不確定"]
  },
  {
    id: "daytime_urgency_impact",
    text: "急尿或頻尿是否影響工作、上課、外出或睡眠？",
    asksFor: ["daytimeUrgencyImpact"],
    symptoms: ["frequency", "urgency"],
    keywords: ["工作", "上課", "外出", "影響", "impact"],
    value: "補足功能影響，讓醫師摘要能區分症狀存在與生活負擔。",
    explanation: "這題收集病人生活影響，不做嚴重度診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.72,
    clinicalWorkflowValue: 0.72,
    safetyPriority: 0.14,
    nextUsefulWhen: ["頻尿或急尿已出現且需量化生活影響"],
    skipWhen: ["已經回答 daytimeUrgencyImpact"],
    options: ["沒有影響", "有一點影響", "明顯影響", "不確定"]
  },
  {
    id: "incomplete_emptying",
    text: "尿完後會覺得膀胱還沒排乾淨嗎？",
    asksFor: ["incompleteEmptying"],
    symptoms: ["voiding"],
    keywords: ["尿不乾淨", "排不乾淨", "incomplete", "emptying"],
    value: "排尿困難方向中的重要病史欄位。",
    explanation: "補足排尿後感受，協助形成可讀摘要。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.18,
    nextUsefulWhen: ["使用者提到排尿困難、尿流弱或尿不乾淨"],
    skipWhen: ["已經回答 incompleteEmptying"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "weak_stream",
    text: "尿流有變細、變弱或斷斷續續嗎？",
    asksFor: ["weakStream"],
    symptoms: ["voiding"],
    keywords: ["尿流弱", "尿流細", "斷斷續續", "weak stream", "slow stream"],
    value: "排尿困難方向中補足尿流型態。",
    explanation: "描述尿流型態，避免用一句排尿困難概括所有狀況。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.18,
    nextUsefulWhen: ["使用者提到尿流弱、排尿不順或尿不出來"],
    skipWhen: ["已經回答 weakStream"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "straining_to_void",
    text: "排尿時需要用力或等很久才尿得出來嗎？",
    asksFor: ["straining"],
    symptoms: ["voiding", "retention"],
    keywords: ["用力", "等很久", "straining", "hesitancy"],
    value: "補足排尿困難的具體行為描述。",
    explanation: "這題讓排尿困難變成更明確的可追問資訊。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.76,
    clinicalWorkflowValue: 0.76,
    safetyPriority: 0.2,
    nextUsefulWhen: ["使用者提到尿不出來、排尿慢或尿流弱"],
    skipWhen: ["已經回答 straining"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "pain_timing",
    text: "疼痛比較常在排尿前、排尿中、排尿後，還是和排尿無關？",
    asksFor: ["painTiming"],
    symptoms: ["pain", "infection"],
    keywords: ["排尿前", "排尿中", "排尿後", "before urination", "during urination", "after urination"],
    value: "疼痛已出現時，時間點能降低疼痛描述模糊性。",
    explanation: "釐清疼痛與排尿的時間關係，不推論診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.8,
    clinicalWorkflowValue: 0.8,
    safetyPriority: 0.22,
    nextUsefulWhen: ["已知道有疼痛或灼熱，需釐清和排尿的關係"],
    skipWhen: ["疼痛位置仍模糊時應先問位置釐清", "已經回答 painTiming"],
    options: ["排尿前", "排尿中", "排尿後", "和排尿無關", "不確定"]
  },
  {
    id: "pain_location_detail",
    text: "疼痛最明顯的位置是尿道、下腹、生殖器、會陰，還是腰背側？",
    asksFor: ["painLocationDetail"],
    symptoms: ["pain", "lower_abdominal_pain", "flank_pain"],
    keywords: ["尿道", "下腹", "生殖器", "會陰", "腰背", "location"],
    value: "模糊疼痛釐清後，補足更可讀的位置欄位。",
    explanation: "這題延續位置釐清，用於摘要而非診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.2,
    nextUsefulWhen: ["已知道有疼痛，但位置需要變成結構化欄位"],
    skipWhen: ["已經回答 painLocationDetail"],
    options: ["尿道", "下腹", "生殖器或陰囊", "會陰", "腰背側", "不確定"]
  },
  {
    id: "lower_abdominal_pain",
    text: "下腹或膀胱附近有疼痛、悶脹或壓迫感嗎？",
    asksFor: ["lowerAbdominalPain"],
    symptoms: ["pain", "lower_abdominal_pain"],
    keywords: ["下腹", "膀胱", "悶脹", "壓迫", "lower abdomen"],
    value: "補足下腹/膀胱附近不適，避免和尿道或生殖器疼痛混在一起。",
    explanation: "將下腹不適獨立成結構化欄位。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.76,
    clinicalWorkflowValue: 0.76,
    safetyPriority: 0.2,
    nextUsefulWhen: ["使用者提到下腹、膀胱附近或位置不清楚的疼痛"],
    skipWhen: ["已經回答 lowerAbdominalPain"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "flank_pain",
    text: "腰部兩側或背側有疼痛嗎？",
    asksFor: ["flankPain"],
    symptoms: ["pain", "flank_pain", "red_flag"],
    keywords: ["腰部", "腰側", "背側", "flank", "back pain"],
    value: "補足腰側疼痛，作為現場優先查看的背景資訊。",
    explanation: "這題只標出病人回報的腰側疼痛，不做病因判斷。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.8,
    clinicalWorkflowValue: 0.8,
    safetyPriority: 0.68,
    nextUsefulWhen: ["使用者提到腰痛、腰側痛、尿痛合併不舒服或感染疑慮"],
    skipWhen: ["已經回答 flankPain"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "fever_chills",
    text: "這次症狀期間有發燒或發冷嗎？",
    asksFor: ["feverChills"],
    symptoms: ["infection", "red_flag"],
    keywords: ["發燒", "發冷", "fever", "chills"],
    value: "紅旗邊界檢查，出現時需讓醫療人員進一步評估。",
    explanation: "這是 safety boundary check，只提示需要醫療人員評估。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.82,
    clinicalWorkflowValue: 0.82,
    safetyPriority: 0.86,
    nextUsefulWhen: ["使用者提到尿痛、感染疑慮、發燒或發冷"],
    skipWhen: ["已經回答 feverChills"],
    options: ["沒有", "有發燒", "有發冷", "兩者都有", "不確定"]
  },
  {
    id: "visible_blood_color",
    text: "尿液顏色比較像粉紅、鮮紅、茶色，還是有血塊？",
    asksFor: ["visibleBloodColor"],
    symptoms: ["hematuria", "red_flag"],
    keywords: ["粉紅", "鮮紅", "茶色", "血塊", "pink", "red", "tea-colored"],
    value: "血尿已出現時，補足病人看到的顏色與血塊描述。",
    explanation: "收集病人觀察到的顏色資訊，不解釋原因。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.78,
    clinicalWorkflowValue: 0.78,
    safetyPriority: 0.7,
    nextUsefulWhen: ["已知道看見紅色、茶色尿或血塊"],
    skipWhen: ["尚未知道是否血尿", "已經回答 visibleBloodColor"],
    answerType: "multi_choice",
    options: ["粉紅", "鮮紅", "茶色或深色", "有血塊", "不確定"]
  },
  {
    id: "similar_symptoms_before",
    text: "以前有發生過類似的泌尿症狀嗎？",
    asksFor: ["similarSymptomsBefore"],
    symptoms: ["context"],
    keywords: ["以前", "之前", "類似", "before", "history"],
    value: "補足是否反覆發生，對醫師閱讀病史有幫助。",
    explanation: "這題補病史背景，不推論復發或診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.7,
    clinicalWorkflowValue: 0.7,
    safetyPriority: 0.14,
    nextUsefulWhen: ["核心症狀已初步清楚後，補足過去是否類似"],
    skipWhen: ["已經回答 similarSymptomsBefore"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "uti_history",
    text: "以前是否曾被醫療人員告知有泌尿道感染？",
    asksFor: ["utiHistory"],
    symptoms: ["infection", "context"],
    keywords: ["感染", "泌尿道感染", "UTI", "urinary tract infection"],
    value: "感染疑慮方向中補足既往病史。",
    explanation: "只記錄既往被告知的病史，不判斷目前是否感染。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.68,
    clinicalWorkflowValue: 0.68,
    safetyPriority: 0.18,
    nextUsefulWhen: ["尿痛、發燒或感染疑慮已出現，且需補既往病史"],
    skipWhen: ["已經回答 utiHistory"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "stone_history",
    text: "以前是否曾有尿路結石或腎結石？",
    asksFor: ["stoneHistory"],
    symptoms: ["flank_pain", "hematuria", "context"],
    keywords: ["結石", "腎結石", "尿路結石", "stone"],
    value: "腰側疼痛或血尿方向中補足既往結石病史。",
    explanation: "這題只記錄既往史，不判斷目前疼痛原因。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.68,
    clinicalWorkflowValue: 0.68,
    safetyPriority: 0.18,
    nextUsefulWhen: ["使用者提到腰側痛、血尿或過去結石"],
    skipWhen: ["已經回答 stoneHistory"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "urologic_surgery_history",
    text: "以前是否做過泌尿科相關手術或處置？",
    asksFor: ["urologicSurgeryHistory"],
    symptoms: ["context"],
    keywords: ["手術", "處置", "導尿", "surgery", "procedure"],
    value: "補足泌尿科重要背景，避免醫師摘要缺少既往處置。",
    explanation: "只收集既往處置背景，不做治療建議。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.64,
    clinicalWorkflowValue: 0.64,
    safetyPriority: 0.12,
    nextUsefulWhen: ["核心症狀已初步清楚後，補足既往泌尿處置"],
    skipWhen: ["已經回答 urologicSurgeryHistory"],
    options: ["沒有", "有", "不確定"]
  },
  {
    id: "diabetes_kidney_history",
    text: "是否有糖尿病、腎臟病，或其他醫師提醒需注意的慢性病？",
    asksFor: ["diabetesKidneyHistory"],
    symptoms: ["context"],
    keywords: ["糖尿病", "腎臟病", "慢性病", "diabetes", "kidney"],
    value: "補足門診前背景，讓醫療人員決定是否需要特別留意。",
    explanation: "記錄背景病史，不產生醫療建議。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.68,
    clinicalWorkflowValue: 0.68,
    safetyPriority: 0.18,
    nextUsefulWhen: ["核心主訴初步清楚後，補足慢性病背景"],
    skipWhen: ["已經回答 diabetesKidneyHistory"],
    answerType: "multi_choice",
    options: ["沒有", "有糖尿病", "有腎臟病", "其他慢性病", "不確定"]
  },
  {
    id: "new_medication_context",
    text: "最近是否開始、停止或調整任何藥物？",
    asksFor: ["newMedicationContext"],
    symptoms: ["context"],
    keywords: ["新藥", "調藥", "停藥", "new medication", "changed medication"],
    value: "補足近期用藥變化背景，不要求病人解釋原因。",
    explanation: "收集近期用藥變化，避免門診前摘要漏掉背景。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.64,
    clinicalWorkflowValue: 0.64,
    safetyPriority: 0.14,
    nextUsefulWhen: ["核心症狀已初步清楚後，補足近期用藥變化"],
    skipWhen: ["已經回答 newMedicationContext"],
    answerType: "multi_choice",
    options: ["沒有", "有開始新藥", "有停藥或調藥", "不確定"]
  },
  {
    id: "clinician_priority",
    text: "如果只能先跟醫師說一件事，你最希望醫師先知道什麼？",
    asksFor: ["clinicianPriority"],
    symptoms: ["general", "context"],
    keywords: ["希望醫師知道", "最重要", "priority"],
    value: "結尾前保留病人主觀優先事項，避免結構化過程抹掉病人的重點。",
    explanation: "這題整理病人最在意的資訊，協助醫師快速進入對話。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.66,
    clinicalWorkflowValue: 0.66,
    safetyPriority: 0.12,
    nextUsefulWhen: ["核心缺口已補足後，準備形成醫師可讀摘要"],
    skipWhen: ["已經回答 clinicianPriority"],
    answerType: "open_text",
    options: ["自由輸入"]
  },
  {
    id: "closing_review",
    text: "還有沒有其他想補充、但前面沒有被問到的事？",
    asksFor: ["closingReview"],
    symptoms: ["general", "context"],
    keywords: ["補充", "其他", "anything else", "closing"],
    value: "結尾檢查，讓病人補充未被題庫捕捉的背景。",
    explanation: "這是關閉前的資訊補洞，不產生新診斷或建議。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.58,
    clinicalWorkflowValue: 0.58,
    safetyPriority: 0.1,
    nextUsefulWhen: ["已完成主要症狀、紅旗與背景欄位後"],
    skipWhen: ["已經回答 closingReview"],
    answerType: "open_text",
    options: ["自由輸入"]
  },
  {
    id: "clarify_pain_burning_conflict",
    text: "我想確認一下：你現在排尿時是否有疼痛、刺痛或灼熱？",
    asksFor: ["painBurningConflict"],
    symptoms: ["pain", "infection"],
    ambiguityType: "pain_burning_conflict",
    keywords: ["前後不一致", "確認", "burns when i pee", "pain when urinating"],
    value: "前後回答不一致時先澄清目前狀態，避免留下互相衝突的病史。",
    explanation: "這是 conflict clarification，不是診斷題。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.62,
    nextUsefulWhen: ["先前記錄沒有尿痛，但新回答提到排尿疼痛或灼熱"],
    skipWhen: ["已經回答 painBurningConflict"],
    options: ["目前沒有", "目前有", "不確定"]
  },
  {
    id: "medication_list",
    text: "今天能不能提供目前藥物資料，例如藥袋、藥單或照片？",
    asksFor: ["medicationListStatus"],
    symptoms: ["context"],
    keywords: ["藥", "藥袋", "藥單", "慢性病", "medication"],
    value: "補足門診前背景資訊，不要求病人背藥名。",
    explanation: "用藥資訊是背景，不要求病人記得藥名。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.7,
    clinicalWorkflowValue: 0.7,
    safetyPriority: 0.18,
    nextUsefulWhen: ["核心主訴已初步清楚後，補足用藥背景"],
    skipWhen: ["已經回答 medicationListStatus"],
    options: ["可以提供", "只記得一部分", "沒有固定用藥", "不確定"]
  }
];

const RAW_COMPACT_PREVISIT_QUESTION_BANK = [
  {
    id: "clarify_pain_location",
    compactFrom: ["clarify_pain_location", "pain_location_detail", "lower_abdominal_pain"],
    text: "你說的疼痛或不舒服，位置比較接近哪裡？",
    asksFor: ["painLocationClarification"],
    symptoms: ["pain", "ambiguous_location"],
    ambiguityType: "pain_location",
    keywords: ["下面痛", "下面不舒服", "那邊痛", "私密處", "尿道痛", "生殖器痛", "會陰", "下腹痛", "pain down there", "private area pain", "hurts down there"],
    value: "疼痛位置模糊時先定位，避免系統直接把病人說法導向特定病因。",
    explanation: "這是釐清題；只把位置變清楚，不做診斷。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.94,
    clinicalWorkflowValue: 0.94,
    safetyPriority: 0.62,
    nextUsefulWhen: ["病人說下面痛、私密處痛、那邊痛，或疼痛位置不清楚"],
    skipWhen: ["已經回答 painLocationClarification", "病人已明確說尿尿時尿道刺痛、下腹痛、腰側痛、生殖器痛或會陰痛"],
    options: ["尿尿時尿道刺痛或灼熱", "下腹或膀胱附近不適", "生殖器或陰囊疼痛", "會陰或肛門前方疼痛", "腰部兩側痛", "不確定"]
  },
  {
    id: "clarify_urinary_symptom_type",
    compactFrom: ["clarify_urinary_symptom_type", "chief_complaint_open", "most_bothersome_symptom"],
    text: "你說的「尿尿怪怪的」比較接近哪一種？",
    asksFor: ["urinarySymptomClarification"],
    symptoms: ["ambiguous_urinary"],
    ambiguityType: "urinary_symptom_type",
    keywords: ["尿尿怪怪", "怪怪的", "不舒服", "怪", "說不出來", "不順", "weird", "not sure", "i don't know"],
    value: "病人只說怪怪的時，先把主訴方向縮小成可追問的症狀類型。",
    explanation: "這題讓模糊主訴進入正確題組，不讓 similarity 過早猜方向。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.94,
    clinicalWorkflowValue: 0.94,
    safetyPriority: 0.58,
    nextUsefulWhen: ["病人只說尿尿怪怪的、下體不舒服、或無法說清楚是哪一類泌尿問題"],
    skipWhen: ["已經回答 urinarySymptomClarification", "病人已明確指出夜尿、急尿、尿痛、血尿、漏尿或尿不出來"],
    options: ["次數變多或晚上起床尿", "尿尿會痛或灼熱", "尿不太出來或尿流變弱", "看到紅色或茶色尿", "漏尿", "不確定"]
  },
  {
    id: "clarify_pain_burning_conflict",
    compactFrom: ["clarify_pain_burning_conflict", "pain_burning"],
    text: "我想確認一下：你現在排尿時是否有疼痛、刺痛或灼熱？",
    asksFor: ["painBurningConflict"],
    symptoms: ["pain", "infection"],
    ambiguityType: "pain_burning_conflict",
    keywords: ["前後不一致", "確認", "burns when i pee", "pain when urinating"],
    value: "前後回答不一致時先確認目前狀態，避免門診摘要留下互相衝突的病史。",
    explanation: "這是矛盾釐清題；只確認病人現在的說法。",
    safety: "clarification",
    safetyLevel: "clarification_only",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.62,
    nextUsefulWhen: ["先前記錄沒有尿痛，但新回答提到排尿疼痛或灼熱"],
    skipWhen: ["已經回答 painBurningConflict"],
    options: ["目前沒有", "目前有", "不確定"]
  },
  {
    id: "compact_primary_concern",
    compactFrom: ["chief_complaint_open", "most_bothersome_symptom", "clarify_urinary_symptom_type"],
    text: "今天最想先讓醫師知道哪一類泌尿問題？",
    asksFor: ["compactPrimaryConcern"],
    symptoms: ["general", "frequency", "nocturia", "urgency", "leakage", "voiding", "pain", "hematuria"],
    keywords: ["主要", "最困擾", "頻尿", "夜尿", "急尿", "漏尿", "尿不出來", "尿痛", "血尿", "main concern", "chief complaint"],
    value: "先取得病人主訴方向，讓後續問題只問醫師接手前需要的最小資訊。",
    explanation: "這是門診前問診入口，不做診斷或分流。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.96,
    clinicalWorkflowValue: 0.96,
    safetyPriority: 0.18,
    nextUsefulWhen: ["尚未知道病人今天最想先說的泌尿問題"],
    skipWhen: ["已經回答 compactPrimaryConcern"],
    answerType: "multi_choice",
    options: ["頻尿、夜尿或急尿", "尿會不小心漏出來", "尿不太出來或尿流變弱", "尿尿疼痛或灼熱", "看到紅色或茶色尿、血塊", "其他泌尿問題", "不確定"]
  },
  {
    id: "compact_duration_bother",
    compactFrom: ["duration", "bother_score", "symptom_start_pattern", "daytime_urgency_impact"],
    text: "這個問題大約多久了？困擾程度大約多高？",
    asksFor: ["durationBother"],
    symptoms: ["general"],
    keywords: ["多久", "開始", "最近", "困擾", "嚴重", "today", "week", "month", "bother", "severity"],
    value: "用一題同時補病程與主觀負擔，讓醫師快速知道時間軸與病人在意程度。",
    explanation: "只整理病程與困擾程度，不判斷原因。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.22,
    nextUsefulWhen: ["已有主訴但尚未建立病程與困擾程度"],
    skipWhen: ["已經回答 durationBother"],
    answerType: "multi_choice",
    options: ["今天開始", "1 到 7 天", "1 到 4 週", "超過 1 個月", "反覆出現", "困擾 0 到 3 分", "困擾 4 到 6 分", "困擾 7 到 10 分", "不確定"]
  },
  {
    id: "compact_storage_symptoms",
    compactFrom: ["nocturia_count", "urgency", "daytime_frequency", "nocturia_sleep_impact", "fluid_context_evening", "urgency_hold_time"],
    text: "頻尿、夜尿或急尿方面，有哪些情況？",
    asksFor: ["compactStorageSymptoms"],
    symptoms: ["frequency", "nocturia", "urgency"],
    keywords: ["頻尿", "一直跑廁所", "白天", "晚上", "夜尿", "急", "忍不住", "nocturia", "frequency", "urgency"],
    value: "把儲尿相關症狀壓成一題，提供醫師後續判斷需要的方向與嚴重度線索。",
    explanation: "只記錄病人回報的儲尿症狀，不推論診斷。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.24,
    nextUsefulWhen: ["病人提到頻尿、夜尿、急尿、一直跑廁所或忍不住"],
    skipWhen: ["已經回答 compactStorageSymptoms"],
    answerType: "multi_choice",
    options: ["白天尿尿次數明顯變多", "晚上睡著後會起床尿尿", "突然很急、很難忍住", "尿意來時幾乎來不及", "睡眠或外出明顯受影響", "以上都沒有", "不確定"]
  },
  {
    id: "compact_leakage_pattern",
    compactFrom: ["leakage", "leakage_trigger", "urgency_hold_time"],
    text: "最近 4 週如果有漏尿，通常是什麼情況？",
    asksFor: ["compactLeakagePattern"],
    symptoms: ["leakage", "urgency"],
    keywords: ["漏尿", "滲出", "褲子", "護墊", "咳嗽", "笑", "運動", "睡覺", "來不及", "leak", "incontinence"],
    value: "漏尿方向只問是否發生與常見情境，避免拆成多題造成負擔。",
    explanation: "只整理漏尿情境，不判斷漏尿類型。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.84,
    clinicalWorkflowValue: 0.84,
    safetyPriority: 0.2,
    nextUsefulWhen: ["病人提到漏尿、忍不住、來不及、護墊或尿會滲出"],
    skipWhen: ["已經回答 compactLeakagePattern"],
    answerType: "multi_choice",
    options: ["沒有漏尿", "來不及到廁所前漏出來", "咳嗽、笑、運動或搬重物時漏", "睡覺時漏", "沒有明顯原因", "不確定"]
  },
  {
    id: "compact_voiding_symptoms",
    compactFrom: ["unable_to_urinate", "current_retention", "incomplete_emptying", "weak_stream", "straining_to_void"],
    text: "排尿不順方面，有哪些情況？",
    asksFor: ["compactVoidingSymptoms"],
    symptoms: ["voiding", "retention"],
    keywords: ["尿不出來", "尿流弱", "尿流細", "排尿困難", "尿不乾淨", "用力", "等很久", "retention", "weak stream"],
    value: "用一題整理排尿困難、尿流、用力與目前是否尿不出來。",
    explanation: "只把排尿不順變成可讀病史；若病人說現在尿不出來，讓現場人員看見。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.72,
    nextUsefulWhen: ["病人提到尿不出來、尿流弱、卡住、尿不乾淨或排尿困難"],
    skipWhen: ["已經回答 compactVoidingSymptoms"],
    answerType: "multi_choice",
    options: ["尿流變細或變弱", "尿尿斷斷續續", "需要用力或等很久才尿得出來", "尿完常覺得沒尿乾淨", "現在仍尿不出來", "以上都沒有", "不確定"]
  },
  {
    id: "compact_pain_systemic",
    compactFrom: ["pain_burning", "pain_timing", "pain_location_detail", "lower_abdominal_pain", "flank_pain", "fever_chills", "systemic_symptoms"],
    text: "疼痛、灼熱或發燒發冷方面，有哪些情況？",
    asksFor: ["compactPainSystemic"],
    symptoms: ["pain", "infection", "flank_pain", "lower_abdominal_pain", "red_flag"],
    keywords: ["痛", "刺痛", "灼熱", "下腹", "膀胱", "腰痛", "腰側", "發燒", "發冷", "burning", "pain", "fever", "chills", "flank"],
    value: "一題整理尿痛、位置與系統性症狀，讓醫師知道接下來要追問的方向。",
    explanation: "只標出病人回報的疼痛與發燒發冷，不判斷感染或其他病因。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.9,
    clinicalWorkflowValue: 0.9,
    safetyPriority: 0.82,
    nextUsefulWhen: ["病人提到尿痛、灼熱、下腹痛、腰側痛、發燒或發冷"],
    skipWhen: ["疼痛位置仍模糊時應先問位置釐清", "已經回答 compactPainSystemic"],
    answerType: "multi_choice",
    options: ["尿尿時疼痛、刺痛或灼熱", "下腹或膀胱附近疼痛/悶脹", "腰部兩側或背側痛", "發燒或發冷", "以上都沒有", "不確定"]
  },
  {
    id: "compact_visible_blood",
    compactFrom: ["visible_blood", "hematuria_pattern", "visible_blood_color"],
    text: "有沒有看過尿液變紅、茶色，或看到血塊？",
    asksFor: ["compactVisibleBlood"],
    symptoms: ["hematuria", "red_flag"],
    keywords: ["血尿", "紅色", "茶色", "深色", "血塊", "blood", "clot", "red urine"],
    value: "血尿方向用一題收集是否出現、顏色與血塊，讓醫師接續判斷。",
    explanation: "只記錄病人看到的顏色或血塊，不解釋原因。",
    safety: "priority_notice",
    safetyLevel: "priority_notice",
    workflowValue: 0.92,
    clinicalWorkflowValue: 0.92,
    safetyPriority: 0.86,
    nextUsefulWhen: ["病人提到血尿、紅色尿、茶色尿、深色尿或血塊"],
    skipWhen: ["已經回答 compactVisibleBlood"],
    answerType: "multi_choice",
    options: ["沒有看過", "粉紅或紅色尿", "茶色或深色尿", "看到血塊", "不只一次或最近常出現", "不確定"]
  },
  {
    id: "compact_background_medication",
    compactFrom: ["diabetes_kidney_history", "stone_history", "uti_history", "urologic_surgery_history", "medication_list", "new_medication_context"],
    text: "有哪些背景或資料需要先讓醫師知道？",
    asksFor: ["compactBackgroundMedication"],
    symptoms: ["context"],
    keywords: ["藥", "藥袋", "藥單", "糖尿病", "腎臟病", "結石", "感染", "手術", "導尿", "medication", "history", "diabetes", "kidney"],
    value: "把慢性病、既往泌尿病史與用藥資料合併成一題，避免背景問題拖長流程。",
    explanation: "這題只收集背景與可提供資料，不要求病人背藥名或判斷藥物作用。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.82,
    clinicalWorkflowValue: 0.82,
    safetyPriority: 0.22,
    nextUsefulWhen: ["核心症狀已初步清楚後，補足醫師接手前的重要背景"],
    skipWhen: ["已經回答 compactBackgroundMedication"],
    answerType: "multi_choice",
    options: ["可以提供藥袋、藥單或藥物照片", "最近有開始、停止或調整藥物", "糖尿病或腎臟病", "神經或脊髓相關病史", "曾有結石、泌尿感染、手術或導尿", "以上都沒有", "不確定"]
  },
  {
    id: "compact_closing_note",
    compactFrom: ["clinician_priority", "closing_review"],
    text: "最後，還有什麼想補充給醫師知道？",
    asksFor: ["compactClosingNote"],
    symptoms: ["general", "context"],
    keywords: ["補充", "其他", "希望醫師知道", "最重要", "anything else", "closing", "priority"],
    value: "結尾保留病人沒有被選項涵蓋的重點，避免結構化過程抹掉病人的主觀優先事項。",
    explanation: "這是最後補充題，只收集病人想讓醫師知道的內容。",
    safety: "non_diagnostic",
    safetyLevel: "routine",
    workflowValue: 0.66,
    clinicalWorkflowValue: 0.66,
    safetyPriority: 0.12,
    nextUsefulWhen: ["主要症狀、優先告知線索與背景已大致整理後"],
    skipWhen: ["已經回答 compactClosingNote"],
    answerType: "open_text",
    options: ["自由輸入"]
  }
];

function inferQuestionType(question) {
  if (question.type) return question.type;
  if (question.ambiguityType) return "clarification";
  if (question.safetyLevel === "priority_notice") return "red_flag_check";
  if ((question.asksFor || []).some((field) => /duration|count|frequency|score|impact|pattern|timing/i.test(field))) return "quantification";
  return "follow_up";
}

function inferDomain(question) {
  const symptoms = question.symptoms || [];
  if (question.ambiguityType) return "ambiguity_clarification";
  if (symptoms.includes("nocturia") || symptoms.includes("frequency") || symptoms.includes("urgency") || symptoms.includes("leakage")) return "storage_symptoms";
  if (symptoms.includes("voiding") || symptoms.includes("retention")) return "voiding_symptoms";
  if (symptoms.includes("pain") || symptoms.includes("infection")) return "pain_or_infection_context";
  if (symptoms.includes("hematuria")) return "hematuria_context";
  if (symptoms.includes("flank_pain") || symptoms.includes("lower_abdominal_pain")) return "pain_location_context";
  if (symptoms.includes("context")) return "background_context";
  return "general_history";
}

function inferAmbiguityReduction(question) {
  if (question.ambiguityType) return 0.95;
  if ((question.asksFor || []).some((field) => /duration|bother|count|frequency|pattern|trigger|location/i.test(field))) return 0.7;
  if (question.safetyLevel === "priority_notice") return 0.55;
  return 0.35;
}

function enrichQuestion(question) {
  return Object.assign({
    type: inferQuestionType(question),
    domain: inferDomain(question),
    clinicalValue: question.clinicalWorkflowValue || question.workflowValue || 0,
    ambiguityReduction: inferAmbiguityReduction(question),
    redFlag: question.safetyLevel === "priority_notice",
    avoidWhen: question.skipWhen || [],
    answerType: question.answerType || (question.options?.length ? "single_choice" : "open_text"),
    explanationTemplate: question.explanationTemplate || question.explanation || question.value || ""
  }, question);
}

const LEGACY_QUESTION_BANK = RAW_QUESTION_BANK.map(enrichQuestion);
const COMPACT_PREVISIT_QUESTION_BANK = RAW_COMPACT_PREVISIT_QUESTION_BANK.map(enrichQuestion);
const QUESTION_BANK = COMPACT_PREVISIT_QUESTION_BANK;
const MAX_PREVISIT_QUESTIONS = 12;

if (typeof module !== "undefined") {
  module.exports = {
    QUESTION_BANK,
    LEGACY_QUESTION_BANK,
    COMPACT_PREVISIT_QUESTION_BANK,
    MAX_PREVISIT_QUESTIONS
  };
}

if (typeof window !== "undefined") {
  window.UrologyAdaptiveQuestionBank = {
    QUESTION_BANK,
    LEGACY_QUESTION_BANK,
    COMPACT_PREVISIT_QUESTION_BANK,
    MAX_PREVISIT_QUESTIONS
  };
  window.UrologyAdaptiveQuestioning = Object.assign({}, window.UrologyAdaptiveQuestioning || {}, {
    QUESTION_BANK,
    LEGACY_QUESTION_BANK,
    COMPACT_PREVISIT_QUESTION_BANK,
    MAX_PREVISIT_QUESTIONS
  });
}
}());
